// Sidebar
export const SIDEBAR_VISIBILITY_TOGGLE = "SIDEBAR_VISIBILITY_TOGGLE";
export const SIDEBAR_VISIBILITY_SHOW = "SIDEBAR_VISIBILITY_SHOW";
export const SIDEBAR_VISIBILITY_HIDE = "SIDEBAR_VISIBILITY_HIDE";
export const SIDEBAR_STICKY_TOGGLE = "SIDEBAR_STICKY_TOGGLE";
export const SIDEBAR_STICKY_ENABLE = "SIDEBAR_STICKY_ENABLE";
export const SIDEBAR_STICKY_DISABLE = "SIDEBAR_STICKY_DISABLE";

// Layout
export const LAYOUT_BOXED_TOGGLE = "LAYOUT_BOXED_TOGGLE";
export const LAYOUT_BOXED_ENABLE = "LAYOUT_BOXED_ENABLE";
export const LAYOUT_BOXED_DISABLE = "LAYOUT_BOXED_DISABLE";

// Theme
export const THEME_TOGGLE = "THEME_TOGGLE";

//Auth
export const SIGN_UP = "SIGN_UP"
export const SIGN_UP_PENDING = "SIGN_UP_PENDING"
export const SIGN_UP_ERROR = "SIGN_UP_ERROR"

export const SIGN_IN = "SIGN_IN"
export const SIGN_OUT = "SIGN_OUT"

//Auth Team
export const TEAM_SIGN_UP = "TEAM_SIGN_UP"
export const TEAM_SIGN_IN = "TEAM_SIGN_IN"

//USER
export const RETRIEVE_USER_ACCOUNT = "RETRIEVE_USER_ACCOUNT"
export const SEND_INVITE = "SEND_INVITE"

//Projects
export const GET_PROJECTS = "GET_PROJECTS"
export const CREATE_PROJECT = "CREATE_PROJECT"
export const DELETE_PROJECT = "DELETE_PROJECT"
export const PROJECT_DETAIL = "PROJECT_DETAIL"

//Tasks
export const REMOVE_FETCHED_TASKS = "REMOVE_FETCHED_TASKS"
export const GET_PROJECT_TASKS = "GET_PROJECT_TASKS"
export const ADD_TASK = "ADD_TASK"
export const DELETE_TASK = "DELETE_TASK"
